[package]
name = "astro-float"
version = "0.1.0"
edition = "2021"
authors = ["stencillogic <stencillogic@gmail.com>"]
license = "MIT"
description = "Multiple precision floating point numbers implemented purely in Rust."
categories = ["algorithms", "data-structures", "science"]
keywords = ["bigfloat", "numeric", "decimal", "mathematics", "bignum"]
readme = "README.md"
repository = "https://github.com/stencillogic/astro-float"

[dev-dependencies]
rand = "0.8.5"

[dependencies]
rand = { version = "0.8.5", optional = true }
lazy_static = { version = "1.4.0", default-features = false, features = [] }
itertools = { version = "0.10.3", default-features = false, features = [] }
smallvec = { version = "1.9.0", default-features = false, features = [] }

[features]
default = ["std", "random"]
std = []
random = ["dep:rand"]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1