[package]
name = "num-bigfloat"
version = "0.1.6"
edition = "2021"
authors = ["stencillogic <stencillogic@gmail.com>"]
license = "MIT"
description = "Multiple precision floating point numbers implemented purely in Rust."
categories = ["algorithms", "data-structures", "science"]
keywords = ["big-float", "numeric", "decimal", "mathematics", "bignum"]
readme = "README.md"
repository = "https://github.com/stencillogic/num-bigfloat"

[dev-dependencies]
rand = "0.8.5"

[dependencies]
rand = { version = "0.8.5", optional = true }
itertools = { version = "0.10.3", features = [] }
smallvec = { version = "1.9.0", features = [] }

[features]
default = ["std", "random"]
std = []
random = ["dep:rand"]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1